spring:
  application:
    name: bingo
  datasource:
    url: jdbc:postgresql://localhost:5432/bingo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /api/v1